# You should always specify a full version here to ensure all of your developers
# are running the same version of Node.
FROM node:11.1.0

# Override the base log level (info).
ENV NPM_CONFIG_LOGLEVEL warn

ADD yarn.lock /yarn.lock
ADD package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn && yarn global add typescript ts-node nodemon pino-pretty

WORKDIR /server
ADD . /server

# Build dist folder
# RUN yarn build

EXPOSE 4000
EXPOSE 35729

ENTRYPOINT ["/bin/bash", "/server/run.sh"]
CMD ["start"]

# docker container run -it -p 4000:4000  -v $(pwd):/server server:app
