FROM node:latest

# Create app directory
RUN mkdir /server
WORKDIR /server

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

ENV NODE_PATH=/server/node_modules
ENV PATH=$PATH:/server/node_modules/.bin

# Install libraries
RUN yarn && yarn global add typescript ts-node nodemon pino-pretty

# Bundle app source
COPY . .

# Build dist folder
# RUN yarn build

EXPOSE 4000

ENTRYPOINT ["/bin/bash", "/server/run.sh"]
CMD ["start"]

# docker container run -it -p 4000:4000  -v $(pwd):/server server:app
